//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceImpuestos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceImpuestos.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApp1.ServiceImpuestos.HelloWorldResponse HelloWorld(WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.HelloWorldResponse> HelloWorldAsync(WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SincronizarFechaHoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponse SincronizarFechaHora(WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SincronizarFechaHora", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponse> SincronizarFechaHoraAsync(WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento obtenerCufdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCufd", ReplyAction="*")]
        WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponse obtenerCufd(WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCufd", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponse> obtenerCufdAsync(WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Cufd del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponse EmitirFactura(WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitirFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponse> EmitirFacturaAsync(WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApp1.ServiceImpuestos.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApp1.ServiceImpuestos.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarFechaHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarFechaHora", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequestBody Body;
        
        public SincronizarFechaHoraRequest() {
        }
        
        public SincronizarFechaHoraRequest(WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SincronizarFechaHoraRequestBody {
        
        public SincronizarFechaHoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SincronizarFechaHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SincronizarFechaHoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponseBody Body;
        
        public SincronizarFechaHoraResponse() {
        }
        
        public SincronizarFechaHoraResponse(WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SincronizarFechaHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SincronizarFechaHoraResult;
        
        public SincronizarFechaHoraResponseBody() {
        }
        
        public SincronizarFechaHoraResponseBody(string SincronizarFechaHoraResult) {
            this.SincronizarFechaHoraResult = SincronizarFechaHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCufdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCufd", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequestBody Body;
        
        public obtenerCufdRequest() {
        }
        
        public obtenerCufdRequest(WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCufdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int modelidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nit;
        
        public obtenerCufdRequestBody() {
        }
        
        public obtenerCufdRequestBody(int idambiente, int modelidad, int nit) {
            this.idambiente = idambiente;
            this.modelidad = modelidad;
            this.nit = nit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCufdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCufdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponseBody Body;
        
        public obtenerCufdResponse() {
        }
        
        public obtenerCufdResponse(WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCufdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCufdResult;
        
        public obtenerCufdResponseBody() {
        }
        
        public obtenerCufdResponseBody(string obtenerCufdResult) {
            this.obtenerCufdResult = obtenerCufdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFactura", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequestBody Body;
        
        public EmitirFacturaRequest() {
        }
        
        public EmitirFacturaRequest(WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idambiente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int modelidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cufd;
        
        public EmitirFacturaRequestBody() {
        }
        
        public EmitirFacturaRequestBody(int idambiente, int modelidad, int nit, string Cufd) {
            this.idambiente = idambiente;
            this.modelidad = modelidad;
            this.nit = nit;
            this.Cufd = Cufd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitirFacturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitirFacturaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponseBody Body;
        
        public EmitirFacturaResponse() {
        }
        
        public EmitirFacturaResponse(WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitirFacturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmitirFacturaResult;
        
        public EmitirFacturaResponseBody() {
        }
        
        public EmitirFacturaResponseBody(string EmitirFacturaResult) {
            this.EmitirFacturaResult = EmitirFacturaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceImpuestos.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceImpuestos.WebService1Soap>, WindowsFormsApp1.ServiceImpuestos.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceImpuestos.HelloWorldResponse WindowsFormsApp1.ServiceImpuestos.WebService1Soap.HelloWorld(WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest inValue = new WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.HelloWorldRequestBody();
            WindowsFormsApp1.ServiceImpuestos.HelloWorldResponse retVal = ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.HelloWorldResponse> WindowsFormsApp1.ServiceImpuestos.WebService1Soap.HelloWorldAsync(WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest inValue = new WindowsFormsApp1.ServiceImpuestos.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.HelloWorldRequestBody();
            return ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponse WindowsFormsApp1.ServiceImpuestos.WebService1Soap.SincronizarFechaHora(WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest request) {
            return base.Channel.SincronizarFechaHora(request);
        }
        
        public string SincronizarFechaHora() {
            WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest inValue = new WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequestBody();
            WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponse retVal = ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).SincronizarFechaHora(inValue);
            return retVal.Body.SincronizarFechaHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponse> WindowsFormsApp1.ServiceImpuestos.WebService1Soap.SincronizarFechaHoraAsync(WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest request) {
            return base.Channel.SincronizarFechaHoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraResponse> SincronizarFechaHoraAsync() {
            WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest inValue = new WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.SincronizarFechaHoraRequestBody();
            return ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).SincronizarFechaHoraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponse WindowsFormsApp1.ServiceImpuestos.WebService1Soap.obtenerCufd(WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest request) {
            return base.Channel.obtenerCufd(request);
        }
        
        public string obtenerCufd(int idambiente, int modelidad, int nit) {
            WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest inValue = new WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modelidad = modelidad;
            inValue.Body.nit = nit;
            WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponse retVal = ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).obtenerCufd(inValue);
            return retVal.Body.obtenerCufdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponse> WindowsFormsApp1.ServiceImpuestos.WebService1Soap.obtenerCufdAsync(WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest request) {
            return base.Channel.obtenerCufdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.obtenerCufdResponse> obtenerCufdAsync(int idambiente, int modelidad, int nit) {
            WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest inValue = new WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.obtenerCufdRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modelidad = modelidad;
            inValue.Body.nit = nit;
            return ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).obtenerCufdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponse WindowsFormsApp1.ServiceImpuestos.WebService1Soap.EmitirFactura(WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest request) {
            return base.Channel.EmitirFactura(request);
        }
        
        public string EmitirFactura(int idambiente, int modelidad, int nit, string Cufd) {
            WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest inValue = new WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modelidad = modelidad;
            inValue.Body.nit = nit;
            inValue.Body.Cufd = Cufd;
            WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponse retVal = ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).EmitirFactura(inValue);
            return retVal.Body.EmitirFacturaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponse> WindowsFormsApp1.ServiceImpuestos.WebService1Soap.EmitirFacturaAsync(WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest request) {
            return base.Channel.EmitirFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceImpuestos.EmitirFacturaResponse> EmitirFacturaAsync(int idambiente, int modelidad, int nit, string Cufd) {
            WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest inValue = new WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequest();
            inValue.Body = new WindowsFormsApp1.ServiceImpuestos.EmitirFacturaRequestBody();
            inValue.Body.idambiente = idambiente;
            inValue.Body.modelidad = modelidad;
            inValue.Body.nit = nit;
            inValue.Body.Cufd = Cufd;
            return ((WindowsFormsApp1.ServiceImpuestos.WebService1Soap)(this)).EmitirFacturaAsync(inValue);
        }
    }
}
