//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebSoap.SOperaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOperaciones.OperacionesSoap")]
    public interface OperacionesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClienteWebSoap.SOperaciones.HelloWorldResponse HelloWorld(ClienteWebSoap.SOperaciones.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.HelloWorldResponse> HelloWorldAsync(ClienteWebSoap.SOperaciones.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        ClienteWebSoap.SOperaciones.ObtenerDatosResponse ObtenerDatos(ClienteWebSoap.SOperaciones.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerDatosResponse> ObtenerDatosAsync(ClienteWebSoap.SOperaciones.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponse ObtenerCertificadoMatrimonio(ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponse ObtenerCertificadoDefuncion(ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteWebSoap.SOperaciones.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteWebSoap.SOperaciones.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(ClienteWebSoap.SOperaciones.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(ClienteWebSoap.SOperaciones.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerDatosResult;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(string ObtenerDatosResult) {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest() {
        }
        
        public ObtenerCertificadoNacimientoRequest(ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerCertificadoNacimientoRequestBody() {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse() {
        }
        
        public ObtenerCertificadoNacimientoResponse(ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCertificadoNacimientoResult;
        
        public ObtenerCertificadoNacimientoResponseBody() {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(string ObtenerCertificadoNacimientoResult) {
            this.ObtenerCertificadoNacimientoResult = ObtenerCertificadoNacimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonio", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequestBody Body;
        
        public ObtenerCertificadoMatrimonioRequest() {
        }
        
        public ObtenerCertificadoMatrimonioRequest(ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerCertificadoMatrimonioRequestBody() {
        }
        
        public ObtenerCertificadoMatrimonioRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponseBody Body;
        
        public ObtenerCertificadoMatrimonioResponse() {
        }
        
        public ObtenerCertificadoMatrimonioResponse(ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCertificadoMatrimonioResult;
        
        public ObtenerCertificadoMatrimonioResponseBody() {
        }
        
        public ObtenerCertificadoMatrimonioResponseBody(string ObtenerCertificadoMatrimonioResult) {
            this.ObtenerCertificadoMatrimonioResult = ObtenerCertificadoMatrimonioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequestBody Body;
        
        public ObtenerCertificadoDefuncionRequest() {
        }
        
        public ObtenerCertificadoDefuncionRequest(ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerCertificadoDefuncionRequestBody() {
        }
        
        public ObtenerCertificadoDefuncionRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponseBody Body;
        
        public ObtenerCertificadoDefuncionResponse() {
        }
        
        public ObtenerCertificadoDefuncionResponse(ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCertificadoDefuncionResult;
        
        public ObtenerCertificadoDefuncionResponseBody() {
        }
        
        public ObtenerCertificadoDefuncionResponseBody(string ObtenerCertificadoDefuncionResult) {
            this.ObtenerCertificadoDefuncionResult = ObtenerCertificadoDefuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperacionesSoapChannel : ClienteWebSoap.SOperaciones.OperacionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesSoapClient : System.ServiceModel.ClientBase<ClienteWebSoap.SOperaciones.OperacionesSoap>, ClienteWebSoap.SOperaciones.OperacionesSoap {
        
        public OperacionesSoapClient() {
        }
        
        public OperacionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebSoap.SOperaciones.HelloWorldResponse ClienteWebSoap.SOperaciones.OperacionesSoap.HelloWorld(ClienteWebSoap.SOperaciones.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClienteWebSoap.SOperaciones.HelloWorldRequest inValue = new ClienteWebSoap.SOperaciones.HelloWorldRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.HelloWorldRequestBody();
            ClienteWebSoap.SOperaciones.HelloWorldResponse retVal = ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.HelloWorldResponse> ClienteWebSoap.SOperaciones.OperacionesSoap.HelloWorldAsync(ClienteWebSoap.SOperaciones.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.HelloWorldResponse> HelloWorldAsync() {
            ClienteWebSoap.SOperaciones.HelloWorldRequest inValue = new ClienteWebSoap.SOperaciones.HelloWorldRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.HelloWorldRequestBody();
            return ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebSoap.SOperaciones.ObtenerDatosResponse ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerDatos(ClienteWebSoap.SOperaciones.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public string ObtenerDatos(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerDatosRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerDatosRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            ClienteWebSoap.SOperaciones.ObtenerDatosResponse retVal = ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerDatosResponse> ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerDatosAsync(ClienteWebSoap.SOperaciones.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerDatosResponse> ObtenerDatosAsync(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerDatosRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerDatosRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponse ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerCertificadoNacimiento(ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public string ObtenerCertificadoNacimiento(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.CI = CI;
            ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponse retVal = ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponse> ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerCertificadoNacimientoAsync(ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponse ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerCertificadoMatrimonio(ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonio(request);
        }
        
        public string ObtenerCertificadoMatrimonio(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.CI = CI;
            ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponse retVal = ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerCertificadoMatrimonio(inValue);
            return retVal.Body.ObtenerCertificadoMatrimonioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponse> ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerCertificadoMatrimonioAsync(ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerCertificadoMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponse ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerCertificadoDefuncion(ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest request) {
            return base.Channel.ObtenerCertificadoDefuncion(request);
        }
        
        public string ObtenerCertificadoDefuncion(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.CI = CI;
            ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponse retVal = ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerCertificadoDefuncion(inValue);
            return retVal.Body.ObtenerCertificadoDefuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponse> ClienteWebSoap.SOperaciones.OperacionesSoap.ObtenerCertificadoDefuncionAsync(ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest request) {
            return base.Channel.ObtenerCertificadoDefuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(string CI) {
            ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest inValue = new ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new ClienteWebSoap.SOperaciones.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body.CI = CI;
            return ((ClienteWebSoap.SOperaciones.OperacionesSoap)(this)).ObtenerCertificadoDefuncionAsync(inValue);
        }
    }
}
