//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceBanco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBanco.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApp1.ServiceBanco.HelloWorldResponse HelloWorld(WindowsFormsApp1.ServiceBanco.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceBanco.HelloWorldResponse> HelloWorldAsync(WindowsFormsApp1.ServiceBanco.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento us del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacion", ReplyAction="*")]
        WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponse ObtenerCotizacion(WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponse> ObtenerCotizacionAsync(WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceBanco.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApp1.ServiceBanco.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceBanco.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApp1.ServiceBanco.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequestBody Body;
        
        public ObtenerCotizacionRequest() {
        }
        
        public ObtenerCotizacionRequest(WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string us;
        
        public ObtenerCotizacionRequestBody() {
        }
        
        public ObtenerCotizacionRequestBody(string us) {
            this.us = us;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponseBody Body;
        
        public ObtenerCotizacionResponse() {
        }
        
        public ObtenerCotizacionResponse(WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerCotizacionResult;
        
        public ObtenerCotizacionResponseBody() {
        }
        
        public ObtenerCotizacionResponseBody(string ObtenerCotizacionResult) {
            this.ObtenerCotizacionResult = ObtenerCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceBanco.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceBanco.WebService1Soap>, WindowsFormsApp1.ServiceBanco.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceBanco.HelloWorldResponse WindowsFormsApp1.ServiceBanco.WebService1Soap.HelloWorld(WindowsFormsApp1.ServiceBanco.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApp1.ServiceBanco.HelloWorldRequest inValue = new WindowsFormsApp1.ServiceBanco.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp1.ServiceBanco.HelloWorldRequestBody();
            WindowsFormsApp1.ServiceBanco.HelloWorldResponse retVal = ((WindowsFormsApp1.ServiceBanco.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceBanco.HelloWorldResponse> WindowsFormsApp1.ServiceBanco.WebService1Soap.HelloWorldAsync(WindowsFormsApp1.ServiceBanco.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceBanco.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApp1.ServiceBanco.HelloWorldRequest inValue = new WindowsFormsApp1.ServiceBanco.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp1.ServiceBanco.HelloWorldRequestBody();
            return ((WindowsFormsApp1.ServiceBanco.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponse WindowsFormsApp1.ServiceBanco.WebService1Soap.ObtenerCotizacion(WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest request) {
            return base.Channel.ObtenerCotizacion(request);
        }
        
        public string ObtenerCotizacion(string us) {
            WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest inValue = new WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest();
            inValue.Body = new WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequestBody();
            inValue.Body.us = us;
            WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponse retVal = ((WindowsFormsApp1.ServiceBanco.WebService1Soap)(this)).ObtenerCotizacion(inValue);
            return retVal.Body.ObtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponse> WindowsFormsApp1.ServiceBanco.WebService1Soap.ObtenerCotizacionAsync(WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest request) {
            return base.Channel.ObtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceBanco.ObtenerCotizacionResponse> ObtenerCotizacionAsync(string us) {
            WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest inValue = new WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequest();
            inValue.Body = new WindowsFormsApp1.ServiceBanco.ObtenerCotizacionRequestBody();
            inValue.Body.us = us;
            return ((WindowsFormsApp1.ServiceBanco.WebService1Soap)(this)).ObtenerCotizacionAsync(inValue);
        }
    }
}
